### PR TITLE
Python script checkers

### PR DESCRIPTION
**Pull request by lpascal-ledger**
If this code is to last (and I think so), we better have some checks on it.
I've cleaned mostly aesthetic issues highlighted by the checks, however there remains:

- copy-paste issues (functions like `merge_json`, `run_cmd`, `git_setup`)
- dead code? (all the `create_app_list/app_load_params_utils.py` file)
- type issues
  - in particular, nearly every dictionary access in `build_and_tests` are performed through `dict.get`, meaning all the related variable could be `None`, which clearly is not the case given how they are manipulated. I was under the impression that the parsed JSON was under our control, and so that we could trust its content and drop these `dict.get` for classic `dict[index]` access, but I'm not sure.
  - similar issue in `create_app_list.app_load_params_check`
  - there is something fishy in `create_app_list/main.py:61`: `variant_json` is a list, while `merge_json` accept dictionnaries. Not sure if it works (it seems to :shrug: ).

### CODE REVIEW

**Comment by sgliner-ledger** [comment]
Do you want to merge this into develop or in your branch ? :thinking:

**Comment by lpascal-ledger** [comment]
I wanted to check if the PR would update to `develop` once the other branch is merged into `develop`.
If I back the branch into `develop` immediately, the commits of #7 would be displayed here.

**Comment by sgliner-ledger** [comment]
Alright :) However I think we should fix all the checks before merging into develop. How do you want to proceed ?

**Comment by lpascal-ledger** [comment]
As you wish really. I could change things but as I'm not clear on the odds and ends, I could just break the code thinking I fix it.
What do you think of current `mypy` output? Is there obvious fixers or does it require to change the code deeply?

**Comment by lpascal-ledger** [comment]
Here, less errors.
2 issues remains with `mypy`, but these are on you as I don't get how it works: `merge_json` is called with a `list` instead of a `dict` twice.

**Review by sgliner-ledger — APPROVED** [review]

**Pull request merged**
