### PR TITLE
Explicit what some operations mean

### PR DESCRIPTION
**Pull request by lpascal-ledger**

### CODE REVIEW

**Review by sgliner-ledger — APPROVED** [review]

**Comment by lpascal-ledger** [comment]
Should we trigger the "Required" workflows by hand?

**Comment by sgliner-ledger** [comment]
You can remove them manually from the repo indeed :)

**Comment by lpascal-ledger** [comment]
Remove?

**Comment by sgliner-ledger** [comment]
Remove :) 
It is not an app repository so we don't need the guideline enforcer. 
These checks are added by default by the script in the branches settings

**Pull request merged**
